participant-index:
  path: /participant
  controller: App\Controller\ParticipantController::index
  methods: ['get']

participant-show:
  path: /participant/{id}
  controller: App\Controller\ParticipantController::show
  methods: ['get']

participant-post:
  path: /participant
  controller: App\Controller\ParticipantController::post
  methods: ['post']

participant-put:
  path: /participant/{id}
  controller: App\Controller\ParticipantController::put
  methods: ['put']

participant-delete:
  path: /participant/{id}
  controller: App\Controller\ParticipantController::delete
  methods: ['delete']
